INSERT INTO party (name,country_id,url_id) VALUES ('Australia First Party (NSW) Incorporated',13,'http://aec.gov.au/Parties_and_Representatives/Party_Registration/Registered_parties/afirst.htm');
INSERT INTO party (name,country_id,url_id) VALUES ('Australian Democrats',13,'http://aec.gov.au/Parties_and_Representatives/Party_Registration/Registered_parties/ad.htm');
INSERT INTO party (name,country_id,url_id) VALUES ('Australian Fishing and Lifestyle Party',13,'http://aec.gov.au/Parties_and_Representatives/Party_Registration/Registered_parties/aflp.htm');
INSERT INTO party (name,country_id,url_id) VALUES ('Australian Greens',13,'http://aec.gov.au/Parties_and_Representatives/Party_Registration/Registered_parties/ag.htm');
INSERT INTO party (name,country_id,url_id) VALUES ('Australian Sex Party',13,'http://aec.gov.au/Parties_and_Representatives/Party_Registration/Registered_parties/austsp.htm');
INSERT INTO party (name,country_id,url_id) VALUES ('Carers Alliance',13,'http://aec.gov.au/Parties_and_Representatives/Party_Registration/Registered_parties/ca.htm');
INSERT INTO party (name,country_id,url_id) VALUES ('Christian Democratic Party (Fred Nile Group)',13,'http://aec.gov.au/Parties_and_Representatives/Party_Registration/Registered_parties/files/cdp.pdf');
INSERT INTO party (name,country_id,url_id) VALUES ('Citizens Electoral Council of Australia',13,'http://aec.gov.au/Parties_and_Representatives/Party_Registration/Registered_parties/cec.htm');
INSERT INTO party (name,country_id,url_id) VALUES ('Communist Alliance',13,'http://aec.gov.au/Parties_and_Representatives/party_registration/Registered_parties/comm.htm');
INSERT INTO party (name,country_id,url_id) VALUES ('Country Liberals (Northern Territory)',13,'http://aec.gov.au/Parties_and_Representatives/Party_Registration/Registered_parties/cl-nt.pdf');
INSERT INTO party (name,country_id,url_id) VALUES ('Democratic Labor Party (DLP) of Australia',13,'http://aec.gov.au/Parties_and_Representatives/Party_Registration/Registered_parties/dlpa.htm');
INSERT INTO party (name,country_id,url_id) VALUES ('Family First Party',13,'http://aec.gov.au/Parties_and_Representatives/Party_Registration/Registered_parties/ffp.htm');
INSERT INTO party (name,country_id,url_id) VALUES ('Liberal Party of Australia',13,'http://aec.gov.au/Parties_and_Representatives/Party_Registration/Registered_parties/lpa.htm');
INSERT INTO party (name,country_id,url_id) VALUES ('National Party of Australia',13,'http://aec.gov.au/Parties_and_Representatives/Party_Registration/Registered_parties/npa.htm');
INSERT INTO party (name,country_id,url_id) VALUES ('Non-Custodial Parents Party (Equal Parenting)',13,'http://aec.gov.au/Parties_and_Representatives/Party_Registration/Registered_parties/ep.htm');
INSERT INTO party (name,country_id,url_id) VALUES ('One Nation',13,'http://aec.gov.au/Parties_and_Representatives/Party_Registration/Registered_parties/on.htm');
INSERT INTO party (name,country_id,url_id) VALUES ('Senator On-Line',13,'http://aec.gov.au/Parties_and_Representatives/Party_Registration/Registered_parties/sol.htm');
INSERT INTO party (name,country_id,url_id) VALUES ('Shooters and Fishers Party',13,'http://aec.gov.au/Parties_and_Representatives/Party_Registration/Registered_parties/shooters-fishers.pdf');
INSERT INTO party (name,country_id,url_id) VALUES ('Socialist Alliance',13,'http://aec.gov.au/Parties_and_Representatives/Party_Registration/Registered_parties/sa.htm');
INSERT INTO party (name,country_id,url_id) VALUES ('Socialist Equality Party',13,'http://aec.gov.au/Parties_and_Representatives/Party_Registration/Registered_parties/sep.htm');
